# Generated by Django 5.1.1 on 2025-11-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='image_url',
        ),
        migrations.AddField(
            model_name='perfume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='perfume_images/'),
        ),
    ]
