# Generated by Django 5.1.1 on 2026-01-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0005_category_remove_cartitem_perfume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('shipping', 'Home Delivery'), ('pickup', 'Store Pickup'), ('pep_paxi', 'PEP/PAXI Delivery')], default='shipping', max_length=20),
        ),
    ]
