# Generated by Django 5.1.1 on 2026-01-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0006_order_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('eft', 'EFT/Swift Transfer'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('other', 'Other')], default='eft', max_length=20),
        ),
    ]
