# Generated by Django 5.1.1 on 2026-01-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0007_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('eft', 'EFT/Swift Transfer'), ('bobpay', 'BobPay (Similar to PayPal)')], default='eft', max_length=20),
        ),
    ]
