# Generated by Django 5.1.1 on 2025-11-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='123 Luxury Avenue', max_length=255)),
                ('city', models.CharField(default='New York', max_length=100)),
                ('state', models.CharField(default='NY', max_length=100)),
                ('zip_code', models.CharField(default='10001', max_length=20)),
                ('email', models.EmailField(default='contact@essence.com', max_length=254)),
                ('phone', models.CharField(default='+1 (555) 123-4567', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
    ]
