# Generated by Django 5.1.1 on 2025-11-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='Standard Bank', max_length=100)),
                ('account_holder_name', models.CharField(default='Essence Luxury Perfumes', max_length=255)),
                ('account_number', models.CharField(default='0000000000', max_length=50)),
                ('branch_code', models.CharField(default='000000', max_length=20)),
                ('branch_name', models.CharField(default='Sandton City', max_length=100)),
                ('swift_code', models.CharField(blank=True, default='SBZAZAJJ', max_length=20, null=True)),
                ('reference_instruction', models.TextField(blank=True, default='Use your order number as reference')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banking Details',
                'verbose_name_plural': 'Banking Details',
            },
        ),
    ]
