# Generated by Django 5.1.1 on 2025-11-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_proofofpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid to developer', max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='Date when payment was recorded')),
                ('reference', models.CharField(help_text='Payment reference number', max_length=255)),
                ('proof_of_payment', models.FileField(blank=True, help_text='Proof of payment file', null=True, upload_to='developer_payments/')),
                ('orders_included', models.TextField(blank=True, help_text='Serialized list of order IDs included in this payment')),
                ('processed', models.BooleanField(default=False, help_text='Whether payment has been processed externally')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
