# Generated by Django 5.1.1 on 2026-01-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_developerpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerpayment',
            name='payment_method',
            field=models.CharField(choices=[('eft', 'EFT/Swift Transfer'), ('bobpay', 'BobPay'), ('bank_transfer', 'Bank Transfer'), ('e_wallet', 'E-Wallet'), ('cheque', 'Cheque')], default='bank_transfer', help_text='Method of payment to developer', max_length=20),
        ),
    ]
