# Generated by Django 5.1.1 on 2026-01-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_developerpayment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerpayment',
            name='payment_method',
            field=models.CharField(choices=[('eft', 'EFT/Swift Transfer'), ('bobpay', 'BobPay')], default='bank_transfer', help_text='Method of payment to developer', max_length=20),
        ),
    ]
